package GUI;

import Database.DB;
import Model.Save;
import Model.Validation;
import Model.WarningMsg;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

public class BOM extends javax.swing.JFrame {

    int xMouse;
    int yMouse;

    double avaRawQty;
    String rawStockNo;

    Main_menu menu = new Main_menu();
    String user = "Testing_User";

    public BOM() {
        initComponents();
        tableSettings();
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        topBar = new javax.swing.JLabel();
        btn_Exit = new javax.swing.JButton();
        heading = new javax.swing.JLabel();
        job_No = new javax.swing.JLabel();
        bomDate = new javax.swing.JLabel();
        jobStart = new javax.swing.JLabel();
        jobEnd = new javax.swing.JLabel();
        unit_Product = new javax.swing.JLabel();
        productName = new javax.swing.JLabel();
        btn_Approve = new javax.swing.JButton();
        Approved_By = new javax.swing.JLabel();
        created_By = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(41, 128, 185), 1, true));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        topBar.setBackground(new java.awt.Color(250, 251, 250));
        topBar.setOpaque(true);
        topBar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                topBarMouseDragged(evt);
            }
        });
        topBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                topBarMousePressed(evt);
            }
        });
        jPanel1.add(topBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 1165, 30));

        btn_Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Close_black.png"))); // NOI18N
        btn_Exit.setBorder(null);
        btn_Exit.setBorderPainted(false);
        btn_Exit.setContentAreaFilled(false);
        btn_Exit.setFocusPainted(false);
        btn_Exit.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Close_red_.png"))); // NOI18N
        btn_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ExitActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1166, 1, 34, 32));

        heading.setFont(new java.awt.Font("Calibri", 1, 25)); // NOI18N
        heading.setForeground(new java.awt.Color(41, 128, 185));
        heading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        heading.setText("Bill Of Materials");
        heading.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(heading, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 32, 1200, 30));

        job_No.setBackground(new java.awt.Color(255, 255, 255));
        job_No.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        job_No.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.add(job_No, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 230, 25));

        bomDate.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        bomDate.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(bomDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 80, 150, 25));

        jobStart.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jobStart.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(jobStart, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 130, 150, 25));

        jobEnd.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jobEnd.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(jobEnd, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 130, 150, 25));

        unit_Product.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        unit_Product.setForeground(new java.awt.Color(0, 102, 204));
        unit_Product.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(unit_Product, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 180, 80, 25));

        productName.setBackground(new java.awt.Color(255, 255, 255));
        productName.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        productName.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.add(productName, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 360, 20));

        btn_Approve.setBackground(new java.awt.Color(41, 128, 185));
        btn_Approve.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        btn_Approve.setForeground(new java.awt.Color(255, 255, 255));
        btn_Approve.setText("Approve");
        btn_Approve.setBorder(null);
        btn_Approve.setBorderPainted(false);
        btn_Approve.setContentAreaFilled(false);
        btn_Approve.setFocusPainted(false);
        btn_Approve.setOpaque(true);
        btn_Approve.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_ApproveMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_ApproveMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_ApproveMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_ApproveMouseReleased(evt);
            }
        });
        btn_Approve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ApproveActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Approve, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 580, 140, 30));

        Approved_By.setBackground(new java.awt.Color(255, 255, 255));
        Approved_By.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Approved_By.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Approved_By.setText("Approved By - SUPER_ADMIN   On  2018-07-30");
        Approved_By.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        Approved_By.setIconTextGap(0);
        jPanel1.add(Approved_By, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 675, 280, 20));

        created_By.setBackground(new java.awt.Color(255, 255, 255));
        created_By.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        created_By.setText("Created By - UserName   On  2018-07-26");
        created_By.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        created_By.setIconTextGap(0);
        jPanel1.add(created_By, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 675, 260, 20));

        table.setBackground(new java.awt.Color(204, 204, 255));
        table.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "JOB No", "Production Name", "Start Date", "Finish Date", "Approval"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(table);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 1080, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1200, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ExitActionPerformed
        //System.exit(0);
        this.dispose();
    }//GEN-LAST:event_btn_ExitActionPerformed

    private void topBarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_topBarMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_topBarMousePressed

    private void topBarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_topBarMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_topBarMouseDragged

    private void btn_ApproveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ApproveMouseEntered
        btn_Approve.setBackground(new Color(31, 97, 141));
    }//GEN-LAST:event_btn_ApproveMouseEntered

    private void btn_ApproveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ApproveMouseExited
        btn_Approve.setBackground(new Color(41, 128, 185));
    }//GEN-LAST:event_btn_ApproveMouseExited

    private void btn_ApproveMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ApproveMousePressed
        btn_Approve.setBackground(new Color(21, 67, 96));
    }//GEN-LAST:event_btn_ApproveMousePressed

    private void btn_ApproveMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ApproveMouseReleased
        btn_Approve.setBackground(new Color(31, 97, 141));
    }//GEN-LAST:event_btn_ApproveMouseReleased

    private void btn_ApproveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ApproveActionPerformed
         
        DefaultTableModel dtm = (DefaultTableModel)table.getModel();
        try {

            for (int i = 0; i < dtm.getRowCount(); i++) {
                  if(Boolean.parseBoolean(table.getValueAt(i,5).toString())==true){
                DB.iud("UPDATE bill_of_matrial SET approved = '"+1+"' where job_id='"+table.getValueAt(i,1).toString()+"'");
                  }
            }

            new Save().setVisible(true);

        } catch (Exception e) {
            e.printStackTrace();
        }
        dtm.setRowCount(0);
        loadData();
    }//GEN-LAST:event_btn_ApproveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BOM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BOM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BOM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BOM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BOM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Approved_By;
    private javax.swing.JLabel bomDate;
    private javax.swing.JButton btn_Approve;
    private javax.swing.JButton btn_Exit;
    private javax.swing.JLabel created_By;
    private javax.swing.JLabel heading;
    public javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel jobEnd;
    private javax.swing.JLabel jobStart;
    private javax.swing.JLabel job_No;
    private javax.swing.JLabel productName;
    private javax.swing.JTable table;
    private javax.swing.JLabel topBar;
    private javax.swing.JLabel unit_Product;
    // End of variables declaration//GEN-END:variables

    private void tableSettings() {
         JTableHeader tableHeader = table.getTableHeader();
        tableHeader.setFont(new Font("Calibri", Font.BOLD, 14)); // change table header font
        // change Horizontal Alignment in Header Text
        ((DefaultTableCellRenderer) tableHeader.getDefaultRenderer()).setHorizontalAlignment(JLabel.CENTER);

        // set Column Alligment to CENTER
        DefaultTableCellRenderer center = new DefaultTableCellRenderer();
        center.setHorizontalAlignment(JLabel.CENTER);

        // set Column Alligment to RIGHT
        DefaultTableCellRenderer right = new DefaultTableCellRenderer();
        right.setHorizontalAlignment(JLabel.RIGHT);

        table.getColumnModel().getColumn(0).setCellRenderer(center);
        table.getColumnModel().getColumn(1).setCellRenderer(center);
        table.getColumnModel().getColumn(3).setCellRenderer(center);
        table.getColumnModel().getColumn(4).setCellRenderer(right);

    }

    private void loadData() {

        DefaultTableModel dtm = (DefaultTableModel) table.getModel();
        try {
            ResultSet rs = DB.search("SELECT job_id,req_department,start_date,finish_date,state FROM bill_of_matrial where approved='"+0+"'");
            int rowNo = 1;
            while (rs.next()) {
                Vector v = new Vector();
                v.add(rowNo++);
                v.add(rs.getString("job_id"));
                v.add(rs.getString("req_department"));
                v.add(rs.getString("start_date"));
                v.add(rs.getString("finish_date"));
                v.add(false);
                dtm.addRow(v);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    
}
