package GUI;

import Database.DB;
import Model.Save;
import Model.Validation;
import java.awt.Color;
import static java.awt.Color.RED;
import java.sql.ResultSet;
import java.time.LocalDate;
import javax.swing.JOptionPane;

public class Customer_Registation extends javax.swing.JFrame {

    public Customer_Registation() {
        initComponents();
        generateID();
    }
    String user = "";

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        first_name = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        last_name = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        nic_no = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        business_name = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        street_name = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        personal_city = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        telephone = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        mobile = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        business_city = new javax.swing.JTextField();
        sameAsAbove = new javax.swing.JCheckBox();
        btn_Cancel = new javax.swing.JButton();
        btn_Add = new javax.swing.JButton();
        business_street = new javax.swing.JTextField();
        grade = new javax.swing.JComboBox<>();
        customerID = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel22 = new javax.swing.JLabel();
        credit_period = new javax.swing.JTextField();
        credit_limit = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(108, 108, 108));
        jPanel1.setPreferredSize(new java.awt.Dimension(1120, 620));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 25)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(41, 128, 185));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Custormer Registation");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 35));

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(66, 73, 73));
        jLabel2.setText("Grade");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 70, 70, 25));

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(66, 73, 73));
        jLabel3.setText("First Name");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 90, 25));

        first_name.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        first_name.setForeground(new java.awt.Color(39, 55, 70));
        first_name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                first_nameKeyTyped(evt);
            }
        });
        jPanel1.add(first_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 250, 25));

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(66, 73, 73));
        jLabel4.setText("Last Name");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 130, -1, 25));

        last_name.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        last_name.setForeground(new java.awt.Color(39, 55, 70));
        last_name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                last_nameKeyTyped(evt);
            }
        });
        jPanel1.add(last_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 130, 250, 25));

        jLabel16.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(66, 73, 73));
        jLabel16.setText("NIC No");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 130, 50, 25));

        nic_no.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        nic_no.setForeground(new java.awt.Color(39, 55, 70));
        nic_no.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nic_noKeyTyped(evt);
            }
        });
        jPanel1.add(nic_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 130, 200, 25));

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(66, 73, 73));
        jLabel5.setText("Business Name");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 100, 25));

        business_name.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        business_name.setForeground(new java.awt.Color(39, 55, 70));
        business_name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                business_nameKeyTyped(evt);
            }
        });
        jPanel1.add(business_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 880, 25));

        jLabel17.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        jLabel17.setText("Personal Address");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 120, 25));

        jLabel7.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(66, 73, 73));
        jLabel7.setText("Street Name");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 90, 25));

        street_name.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        street_name.setForeground(new java.awt.Color(39, 55, 70));
        street_name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                street_nameKeyTyped(evt);
            }
        });
        jPanel1.add(street_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 480, 25));

        jLabel18.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(66, 73, 73));
        jLabel18.setText("City");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 250, 50, 25));

        personal_city.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        personal_city.setForeground(new java.awt.Color(39, 55, 70));
        personal_city.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                personal_cityKeyTyped(evt);
            }
        });
        jPanel1.add(personal_city, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 250, 260, 25));

        jLabel8.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(66, 73, 73));
        jLabel8.setText("Telephone No");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 90, 25));

        telephone.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        telephone.setForeground(new java.awt.Color(39, 55, 70));
        telephone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                telephoneKeyTyped(evt);
            }
        });
        jPanel1.add(telephone, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 380, 170, 25));

        jLabel9.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(66, 73, 73));
        jLabel9.setText("Mobile No");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 380, -1, 25));

        jLabel10.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(66, 73, 73));
        jLabel10.setText("Email");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 380, -1, 25));

        mobile.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        mobile.setForeground(new java.awt.Color(39, 55, 70));
        mobile.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                mobileKeyTyped(evt);
            }
        });
        jPanel1.add(mobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 380, 180, 25));

        email.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        email.setForeground(new java.awt.Color(39, 55, 70));
        email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                emailKeyTyped(evt);
            }
        });
        jPanel1.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 380, 320, 25));

        jLabel19.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        jLabel19.setText("Business Address");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 120, 25));

        jLabel20.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(66, 73, 73));
        jLabel20.setText("Street Name");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 90, 25));

        jLabel21.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(66, 73, 73));
        jLabel21.setText("City");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 330, 50, 25));

        business_city.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        business_city.setForeground(new java.awt.Color(39, 55, 70));
        business_city.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                business_cityKeyTyped(evt);
            }
        });
        jPanel1.add(business_city, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 330, 260, 25));

        sameAsAbove.setBackground(new java.awt.Color(255, 255, 255));
        sameAsAbove.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        sameAsAbove.setForeground(new java.awt.Color(0, 51, 204));
        sameAsAbove.setText("  Same As Above");
        sameAsAbove.setBorder(null);
        sameAsAbove.setFocusPainted(false);
        sameAsAbove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sameAsAboveMouseClicked(evt);
            }
        });
        jPanel1.add(sameAsAbove, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 150, 25));

        btn_Cancel.setBackground(new java.awt.Color(179, 182, 183));
        btn_Cancel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_Cancel.setText("Cancel");
        btn_Cancel.setBorder(null);
        btn_Cancel.setBorderPainted(false);
        btn_Cancel.setContentAreaFilled(false);
        btn_Cancel.setFocusPainted(false);
        btn_Cancel.setOpaque(true);
        btn_Cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_CancelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_CancelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_CancelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_CancelMouseReleased(evt);
            }
        });
        jPanel1.add(btn_Cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 550, 90, 30));

        btn_Add.setBackground(new java.awt.Color(41, 128, 185));
        btn_Add.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_Add.setForeground(new java.awt.Color(255, 255, 255));
        btn_Add.setText("Save");
        btn_Add.setBorder(null);
        btn_Add.setBorderPainted(false);
        btn_Add.setContentAreaFilled(false);
        btn_Add.setFocusPainted(false);
        btn_Add.setOpaque(true);
        btn_Add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_AddMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_AddMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_AddMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_AddMouseReleased(evt);
            }
        });
        btn_Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AddActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Add, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 550, 90, 30));

        business_street.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        business_street.setForeground(new java.awt.Color(39, 55, 70));
        business_street.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                business_streetKeyTyped(evt);
            }
        });
        jPanel1.add(business_street, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, 480, 25));

        grade.setEditable(true);
        grade.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        grade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Select Grade -", "Brownse", "Gold", "Platinum" }));
        grade.setFocusable(false);
        jPanel1.add(grade, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 70, 150, 25));

        customerID.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        jPanel1.add(customerID, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 250, 25));

        jSeparator1.setForeground(new java.awt.Color(41, 128, 185));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, 610, 10));

        jLabel22.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(66, 73, 73));
        jLabel22.setText("Credit Period (Days)");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, 140, 25));

        credit_period.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        credit_period.setForeground(new java.awt.Color(39, 55, 70));
        credit_period.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                credit_periodKeyTyped(evt);
            }
        });
        jPanel1.add(credit_period, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 470, 170, 25));

        credit_limit.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        credit_limit.setForeground(new java.awt.Color(39, 55, 70));
        credit_limit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                credit_limitKeyTyped(evt);
            }
        });
        jPanel1.add(credit_limit, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 470, 180, 25));

        jLabel23.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(66, 73, 73));
        jLabel23.setText("Credit Limit");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 470, 80, 25));

        jLabel11.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(66, 73, 73));
        jLabel11.setText("Customer ID ");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 90, 25));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_CancelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_CancelMouseEntered
        btn_Cancel.setBackground(new Color(144, 148, 151));
    }//GEN-LAST:event_btn_CancelMouseEntered

    private void btn_CancelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_CancelMouseExited
        btn_Cancel.setBackground(new Color(179, 182, 183));
    }//GEN-LAST:event_btn_CancelMouseExited

    private void btn_CancelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_CancelMousePressed
        btn_Cancel.setBackground(new Color(98, 101, 103));
    }//GEN-LAST:event_btn_CancelMousePressed

    private void btn_CancelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_CancelMouseReleased
        btn_Cancel.setBackground(new Color(144, 148, 151));
    }//GEN-LAST:event_btn_CancelMouseReleased

    private void btn_AddMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_AddMouseEntered
        btn_Add.setBackground(new Color(31, 97, 141));
    }//GEN-LAST:event_btn_AddMouseEntered

    private void btn_AddMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_AddMouseExited
        btn_Add.setBackground(new Color(41, 128, 185));
    }//GEN-LAST:event_btn_AddMouseExited

    private void btn_AddMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_AddMousePressed
        btn_Add.setBackground(new Color(21, 67, 96));
    }//GEN-LAST:event_btn_AddMousePressed

    private void btn_AddMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_AddMouseReleased
        btn_Add.setBackground(new Color(31, 97, 141));
    }//GEN-LAST:event_btn_AddMouseReleased

    private void btn_AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AddActionPerformed
        if (first_name.getText().isEmpty() | nic_no.getText().isEmpty() | street_name.getText().isEmpty() | personal_city.getText().isEmpty() | credit_limit.getText().isEmpty() | credit_period.getText().isEmpty() | mobile.getText().isEmpty() | email.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill all the fields", "Feilds not filled", JOptionPane.INFORMATION_MESSAGE);
        } else if (email.getForeground().equals(RED)) {
            JOptionPane.showMessageDialog(this, "Please enter a correct email address", "Email not Valid", JOptionPane.INFORMATION_MESSAGE);
        } else if (mobile.getText().length() < 10) {
            JOptionPane.showMessageDialog(this, "Please enter a correct mobile no", "mobile not Valid", JOptionPane.INFORMATION_MESSAGE);
        } else if (grade.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Please select a correct grade", "Please select a croeect grade ", JOptionPane.INFORMATION_MESSAGE);
        } else if (nic_no.getText().length() <= 10) {
            if (!(nic_no.getText().trim().matches("^[0-9]{9}[vVxX]$"))) {
                JOptionPane.showMessageDialog(this, "Please enter a correct nic no", "nic not Valid", JOptionPane.INFORMATION_MESSAGE);
            } else {
                try {
                    DB.iud("insert into customer (id_customer,fname,lname,nic,business_name,street,city,telephoneno,mobile,email,state,createby,date_created,grade) Values ('" + customerID.getText() + "','" + first_name.getText() + "','" + last_name.getText() + "','" + nic_no.getText() + "','" + business_name.getText() + "','" + street_name.getText() + "','" + personal_city.getText() + "','" + telephone.getText() + "','" + mobile.getText() + "','" + email.getText() + "','1','" + user + "','" + LocalDate.now() + "','" + grade.getSelectedItem().toString() + "')");
                    DB.iud("insert into customer_business (id_customer,street,city,credit_period,credit_limit) VALUES ('" + customerID.getText() + "','" + business_street.getText() + "','" + business_city.getText() + "','" + credit_period.getText() + "','" + credit_limit.getText() + "')");
                    new Save().setVisible(true);
                    generateID();
                    clearall();
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        }


    }//GEN-LAST:event_btn_AddActionPerformed

    private void first_nameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_first_nameKeyTyped
        Validation.setLettersOnly(evt);
    }//GEN-LAST:event_first_nameKeyTyped

    private void last_nameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_last_nameKeyTyped
        Validation.setLettersOnly(evt);
    }//GEN-LAST:event_last_nameKeyTyped

    private void nic_noKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nic_noKeyTyped

        Validation.setLength(evt, nic_no.getText(), 10);

    }//GEN-LAST:event_nic_noKeyTyped

    private void business_nameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_business_nameKeyTyped
        Validation.setLength(evt, business_name.getText(), 145);
    }//GEN-LAST:event_business_nameKeyTyped

    private void street_nameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_street_nameKeyTyped
        Validation.setLength(evt, street_name.getText(), 45);
    }//GEN-LAST:event_street_nameKeyTyped

    private void personal_cityKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_personal_cityKeyTyped
        Validation.setLength(evt, personal_city.getText(), 25);
    }//GEN-LAST:event_personal_cityKeyTyped

    private void business_streetKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_business_streetKeyTyped
        Validation.setLength(evt, business_street.getText(), 145);
    }//GEN-LAST:event_business_streetKeyTyped

    private void business_cityKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_business_cityKeyTyped
        Validation.setLength(evt, business_city.getText(), 25);
    }//GEN-LAST:event_business_cityKeyTyped

    private void telephoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_telephoneKeyTyped
        Validation.setDigitsOnly(evt);
        Validation.setLength(evt, telephone.getText(), 10);
    }//GEN-LAST:event_telephoneKeyTyped

    private void mobileKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mobileKeyTyped
        Validation.setDigitsOnly(evt);
        Validation.setLength(evt, mobile.getText(), 10);
    }//GEN-LAST:event_mobileKeyTyped

    private void emailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailKeyTyped
        if (Validation.isValidemail(email.getText())) {
            email.setForeground(new Color(39, 55, 70));
        } else {
            email.setForeground(Color.red);
        }
    }//GEN-LAST:event_emailKeyTyped

    private void credit_periodKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_credit_periodKeyTyped
        Validation.setDigitsOnly(evt);
        Validation.setLength(evt, credit_period.getText(), 3);
    }//GEN-LAST:event_credit_periodKeyTyped

    private void credit_limitKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_credit_limitKeyTyped
        Validation.setDigitsOnly(evt);
        Validation.setLength(evt, credit_limit.getText(), 10);
    }//GEN-LAST:event_credit_limitKeyTyped

    private void credit_limitKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_credit_limitKeyReleased

    }//GEN-LAST:event_credit_limitKeyReleased

    private void sameAsAboveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sameAsAboveMouseClicked
        if (sameAsAbove.isSelected()) {
            business_street.setText(street_name.getText());
            business_city.setText(personal_city.getText());
        } else {
            business_street.setText("");
            business_city.setText("");
        }
    }//GEN-LAST:event_sameAsAboveMouseClicked

    private void btn_CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CancelActionPerformed
        clearall();
        generateID();
    }//GEN-LAST:event_btn_CancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Customer_Registation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Customer_Registation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Customer_Registation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Customer_Registation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Customer_Registation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Add;
    private javax.swing.JButton btn_Cancel;
    private javax.swing.JTextField business_city;
    private javax.swing.JTextField business_name;
    private javax.swing.JTextField business_street;
    private javax.swing.JTextField credit_limit;
    private javax.swing.JTextField credit_period;
    private javax.swing.JLabel customerID;
    private javax.swing.JTextField email;
    private javax.swing.JTextField first_name;
    private javax.swing.JComboBox<String> grade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField last_name;
    private javax.swing.JTextField mobile;
    private javax.swing.JTextField nic_no;
    private javax.swing.JTextField personal_city;
    private javax.swing.JCheckBox sameAsAbove;
    private javax.swing.JTextField street_name;
    private javax.swing.JTextField telephone;
    // End of variables declaration//GEN-END:variables

    private void generateID() {
        try {
            ResultSet rs = DB.search("SELECT COUNT(id_customer) AS id FROM customer");
            if (rs.next()) {
                int rowcount = rs.getInt("id");
                rowcount++;
                customerID.setText("CUS" + String.format("%0" + 4 + "d", rowcount));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void clearall() {
        first_name.setText("");
        last_name.setText("");
        street_name.setText("");
        personal_city.setText("");
        nic_no.setText("");
        business_name.setText("");
        business_city.setText("");
        business_street.setText("");
        email.setText("");
        telephone.setText("");
        mobile.setText("");
        grade.setSelectedIndex(0);
        sameAsAbove.setSelected(false);
        credit_limit.setText("");
        credit_period.setText("");

    }
}
