/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Database.DB;
import com.sun.org.apache.bcel.internal.generic.Select;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.DefaultListModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sandalu
 */
public class Employee_Allowance extends javax.swing.JFrame {

    /**
     * Creates new form Employee
     */
    public Employee_Allowance() {
        initComponents();
        jScrollPane5.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Allowance = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        Allowance_ = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        valid_period = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        Discription = new javax.swing.JTextArea();
        ADD = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btn_Save1 = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jScrollPane6 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel29 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        valid_period1 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        Discription1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        ADD1 = new javax.swing.JButton();
        Allowance_1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(1366, 768));
        jPanel1.setMinimumSize(new java.awt.Dimension(1366, 768));
        jPanel1.setPreferredSize(new java.awt.Dimension(1366, 768));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Close_black.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setFocusPainted(false);
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Close_red_.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 0, 34, 32));

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 25)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(41, 128, 185));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Employee Allowance & Deduction");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 30));

        Allowance.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jList1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jList1KeyPressed(evt);
            }
        });
        jScrollPane5.setViewportView(jList1);

        jPanel3.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 55, 200, 90));

        Allowance_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Allowance_ActionPerformed(evt);
            }
        });
        Allowance_.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Allowance_KeyTyped(evt);
            }
        });
        jPanel3.add(Allowance_, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 200, 25));

        jLabel24.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(66, 73, 73));
        jLabel24.setText("Employee");
        jPanel3.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 70, 20));

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField2KeyReleased(evt);
            }
        });
        jPanel3.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 200, 25));
        jPanel3.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 990, 10));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Allowance", "valid period ", "Discription"
            }
        ));
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 980, 280));

        valid_period.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valid_periodActionPerformed(evt);
            }
        });
        jPanel3.add(valid_period, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 110, 170, 25));

        jLabel25.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(66, 73, 73));
        jLabel25.setText("Description");
        jPanel3.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 110, 80, 25));

        Discription.setColumns(20);
        Discription.setRows(5);
        Discription.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                DiscriptionAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane3.setViewportView(Discription);

        jPanel3.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 100, 250, 50));

        ADD.setBackground(new java.awt.Color(41, 128, 185));
        ADD.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ADD.setForeground(new java.awt.Color(255, 255, 255));
        ADD.setText("ADD");
        ADD.setBorder(null);
        ADD.setBorderPainted(false);
        ADD.setContentAreaFilled(false);
        ADD.setFocusPainted(false);
        ADD.setOpaque(true);
        ADD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ADDMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ADDMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ADDMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ADDMouseReleased(evt);
            }
        });
        ADD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADDActionPerformed(evt);
            }
        });
        jPanel3.add(ADD, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 20, 80, 30));

        jLabel28.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(66, 73, 73));
        jLabel28.setText("Amount");
        jPanel3.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 70, 25));

        jLabel30.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(66, 73, 73));
        jLabel30.setText("Valid period ");
        jPanel3.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, 90, 25));

        Allowance.addTab("Allowance", jPanel3);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_Save1.setBackground(new java.awt.Color(41, 128, 185));
        btn_Save1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_Save1.setForeground(new java.awt.Color(255, 255, 255));
        btn_Save1.setText("ADD");
        btn_Save1.setBorder(null);
        btn_Save1.setBorderPainted(false);
        btn_Save1.setContentAreaFilled(false);
        btn_Save1.setFocusPainted(false);
        btn_Save1.setOpaque(true);
        btn_Save1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_Save1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_Save1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_Save1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_Save1MouseReleased(evt);
            }
        });
        btn_Save1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Save1ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_Save1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 110, 80, 30));

        jLabel26.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(66, 73, 73));
        jLabel26.setText("Employee");
        jPanel2.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 70, 20));

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField3KeyReleased(evt);
            }
        });
        jPanel2.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 200, 25));

        jList2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList2MouseClicked(evt);
            }
        });
        jList2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jList2KeyPressed(evt);
            }
        });
        jScrollPane6.setViewportView(jList2);

        jPanel2.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 55, 200, 90));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 990, 10));

        jLabel29.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(66, 73, 73));
        jLabel29.setText("Amount");
        jPanel2.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 70, 25));

        jLabel31.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(66, 73, 73));
        jLabel31.setText("Valid period ");
        jPanel2.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, 90, 25));

        valid_period1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valid_period1ActionPerformed(evt);
            }
        });
        jPanel2.add(valid_period1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 110, 170, 25));

        jLabel27.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(66, 73, 73));
        jLabel27.setText("Description");
        jPanel2.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 110, 80, 25));

        Discription1.setColumns(20);
        Discription1.setRows(5);
        Discription1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                Discription1AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane4.setViewportView(Discription1);

        jPanel2.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 100, 250, 50));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Allowance", "valid period ", "Discription"
            }
        ));
        jTable2.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTable2);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 980, 280));

        ADD1.setBackground(new java.awt.Color(41, 128, 185));
        ADD1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ADD1.setForeground(new java.awt.Color(255, 255, 255));
        ADD1.setText("ADD");
        ADD1.setBorder(null);
        ADD1.setBorderPainted(false);
        ADD1.setContentAreaFilled(false);
        ADD1.setFocusPainted(false);
        ADD1.setOpaque(true);
        ADD1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ADD1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ADD1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ADD1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ADD1MouseReleased(evt);
            }
        });
        ADD1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADD1ActionPerformed(evt);
            }
        });
        jPanel2.add(ADD1, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 20, 80, 30));

        Allowance_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Allowance_1ActionPerformed(evt);
            }
        });
        Allowance_1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Allowance_1KeyTyped(evt);
            }
        });
        jPanel2.add(Allowance_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 200, 25));

        Allowance.addTab("Deduction", jPanel2);

        jPanel1.add(Allowance, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 1070, 510));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1067, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void valid_periodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valid_periodActionPerformed
        Discription.grabFocus();
    }//GEN-LAST:event_valid_periodActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed

    }//GEN-LAST:event_jTextField2ActionPerformed

    private void btn_Save1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Save1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_Save1MouseEntered

    private void btn_Save1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Save1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_Save1MouseExited

    private void btn_Save1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Save1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_Save1MousePressed

    private void btn_Save1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Save1MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_Save1MouseReleased

    private void btn_Save1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Save1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_Save1ActionPerformed

    private void ADDMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ADDMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_ADDMouseEntered

    private void ADDMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ADDMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_ADDMouseExited

    private void ADDMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ADDMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_ADDMousePressed

    private void ADDMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ADDMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_ADDMouseReleased

    private void ADDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADDActionPerformed
        try {
//           
            DB.iud("INSERT INTO allowances VALUES('" + Allowance_.getText() + "','" + valid_period.getText() + "','" + Discription.getText() + "' ");
            
        } catch (Exception e) {
            
        }


    }//GEN-LAST:event_ADDActionPerformed

    private void Allowance_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Allowance_ActionPerformed
        valid_period.grabFocus();
    }//GEN-LAST:event_Allowance_ActionPerformed

    private void DiscriptionAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_DiscriptionAncestorAdded

    }//GEN-LAST:event_DiscriptionAncestorAdded

    private void jTextField2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyReleased
        // TODO add your handling code here:
        try {
            if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {

                jScrollPane5.setVisible(false);
                jTextField2.setText(null);

            } else if (!jTextField2.getText().equals("") && jTextField2.getText() != null) {

                jScrollPane5.setVisible(true);

                ResultSet rs = DB.search("SELECT CONCAT(fname, ' ', lname) AS name FROM employee  WHERE fname LIKE '%" + jTextField2.getText() + "%' or mname LIKE '%" + jTextField2.getText() + "%' or lname LIKE '%" + jTextField2.getText() + "%'");
                Vector v = new Vector();

                while (rs.next()) {

                    v.add(rs.getString("name"));
                }

                jList1.setListData(v);

            } else {

                DefaultListModel dlm = new DefaultListModel();
                jList1.setModel(dlm);
                dlm.clear();

            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jTextField2KeyReleased

    private void Allowance_KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Allowance_KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_Allowance_KeyTyped

    private void jList1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jList1KeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_jList1KeyPressed

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        String a = jList1.getSelectedValue().toString().split("-")[0].trim();
        jTextField2.setText(a);
        jScrollPane5.setVisible(false);
        Allowance_.grabFocus();
    }//GEN-LAST:event_jList1MouseClicked

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3KeyReleased

    private void jList2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jList2MouseClicked

    private void jList2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jList2KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jList2KeyPressed

    private void valid_period1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valid_period1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valid_period1ActionPerformed

    private void Discription1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_Discription1AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_Discription1AncestorAdded

    private void ADD1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ADD1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_ADD1MouseEntered

    private void ADD1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ADD1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_ADD1MouseExited

    private void ADD1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ADD1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_ADD1MousePressed

    private void ADD1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ADD1MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_ADD1MouseReleased

    private void ADD1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADD1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ADD1ActionPerformed

    private void Allowance_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Allowance_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Allowance_1ActionPerformed

    private void Allowance_1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Allowance_1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_Allowance_1KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Employee_Allowance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Employee_Allowance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Employee_Allowance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Employee_Allowance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Employee_Allowance().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ADD;
    private javax.swing.JButton ADD1;
    private javax.swing.JTabbedPane Allowance;
    private javax.swing.JTextField Allowance_;
    private javax.swing.JTextField Allowance_1;
    private javax.swing.JTextArea Discription;
    private javax.swing.JTextArea Discription1;
    private javax.swing.JButton btn_Save1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField valid_period;
    private javax.swing.JTextField valid_period1;
    // End of variables declaration//GEN-END:variables
}
