package GUI;

import Database.DB;
import Model.Save;
import java.awt.Color;
import java.awt.Font;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Vector;
import javax.swing.DefaultCellEditor;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.renderers.SimpleDataRenderer;
import net.sf.jasperreports.view.JasperViewer;

public class hrm_reports extends javax.swing.JFrame {

    public hrm_reports() {
        initComponents();
        loadtoYearcmb();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        department = new javax.swing.JComboBox<>();
        btn_view = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        btn_view1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        leave_dep = new javax.swing.JComboBox<>();
        btn_view2 = new javax.swing.JButton();
        leave_month = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        leave_year = new javax.swing.JComboBox<>();
        jPanel6 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        departments = new javax.swing.JComboBox<>();
        btn_view3 = new javax.swing.JButton();
        leave_month1 = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        leave_year1 = new javax.swing.JComboBox<>();
        emp_name = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        departments1 = new javax.swing.JComboBox<>();
        btn_view4 = new javax.swing.JButton();
        leave_month2 = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        leave_year2 = new javax.swing.JComboBox<>();
        emp_name1 = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        btn_view5 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        departments2 = new javax.swing.JComboBox<>();
        jPanel9 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        departments3 = new javax.swing.JComboBox<>();
        btn_view6 = new javax.swing.JButton();
        emp_name2 = new javax.swing.JComboBox<>();
        jLabel26 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 25)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(41, 128, 185));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Reports - Employee Details");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 990, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 255), 1, true), "Section wise daily attendance", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 1, 14), new java.awt.Color(51, 0, 255))); // NOI18N

        jLabel11.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(66, 73, 73));
        jLabel11.setText("Select date");

        jDateChooser1.setBackground(new java.awt.Color(255, 255, 255));
        jDateChooser1.setForeground(new java.awt.Color(39, 55, 70));
        jDateChooser1.setDateFormatString("yyyy-MM-dd");
        jDateChooser1.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jDateChooser1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jDateChooser1PropertyChange(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(66, 73, 73));
        jLabel10.setText("Select department");

        department.setEditable(true);
        department.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        department.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Select -", "Human Resource", "Production", "Sales & Marketing", "Purchasing", "Finance" }));
        department.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        department.setFocusable(false);
        department.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departmentActionPerformed(evt);
            }
        });

        btn_view.setBackground(new java.awt.Color(179, 182, 183));
        btn_view.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btn_view.setText("View");
        btn_view.setBorder(null);
        btn_view.setBorderPainted(false);
        btn_view.setContentAreaFilled(false);
        btn_view.setFocusPainted(false);
        btn_view.setOpaque(true);
        btn_view.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_viewMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_viewMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_viewMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_viewMouseReleased(evt);
            }
        });
        btn_view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_viewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(department, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(btn_view, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(department, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_view, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 320, 160));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 255), 1, true), "All section attendance - daily", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 1, 14), new java.awt.Color(51, 0, 255))); // NOI18N

        jLabel12.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(66, 73, 73));
        jLabel12.setText("Select date");

        jDateChooser2.setBackground(new java.awt.Color(255, 255, 255));
        jDateChooser2.setForeground(new java.awt.Color(39, 55, 70));
        jDateChooser2.setDateFormatString("yyyy-MM-dd");
        jDateChooser2.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jDateChooser2.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jDateChooser2PropertyChange(evt);
            }
        });

        btn_view1.setBackground(new java.awt.Color(179, 182, 183));
        btn_view1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btn_view1.setText("View");
        btn_view1.setBorder(null);
        btn_view1.setBorderPainted(false);
        btn_view1.setContentAreaFilled(false);
        btn_view1.setFocusPainted(false);
        btn_view1.setOpaque(true);
        btn_view1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_view1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_view1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_view1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_view1MouseReleased(evt);
            }
        });
        btn_view1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_view1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(btn_view1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_view1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 75, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 220, 280, 160));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 255), 1, true), "Section wise leave", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 1, 14), new java.awt.Color(51, 0, 255))); // NOI18N

        jLabel13.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(66, 73, 73));
        jLabel13.setText("Select month");

        jLabel14.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(66, 73, 73));
        jLabel14.setText("Select department");

        leave_dep.setEditable(true);
        leave_dep.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        leave_dep.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Select -", "Human Resource", "Production", "Sales & Marketing", "Purchasing", "Finance" }));
        leave_dep.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        leave_dep.setFocusable(false);
        leave_dep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leave_depActionPerformed(evt);
            }
        });

        btn_view2.setBackground(new java.awt.Color(179, 182, 183));
        btn_view2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btn_view2.setText("View");
        btn_view2.setBorder(null);
        btn_view2.setBorderPainted(false);
        btn_view2.setContentAreaFilled(false);
        btn_view2.setFocusPainted(false);
        btn_view2.setOpaque(true);
        btn_view2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_view2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_view2MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_view2MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_view2MouseReleased(evt);
            }
        });
        btn_view2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_view2ActionPerformed(evt);
            }
        });

        leave_month.setEditable(true);
        leave_month.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        leave_month.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Select -", "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        leave_month.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        leave_month.setFocusable(false);
        leave_month.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leave_monthActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(66, 73, 73));
        jLabel15.setText("Select year");

        leave_year.setEditable(true);
        leave_year.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        leave_year.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        leave_year.setFocusable(false);
        leave_year.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leave_yearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(6, 6, 6)
                        .addComponent(leave_dep, 0, 1, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel15))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(leave_month, 0, 1, Short.MAX_VALUE)
                            .addComponent(leave_year, 0, 1, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(100, Short.MAX_VALUE)
                .addComponent(btn_view2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(leave_year, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(leave_month, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(leave_dep, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_view2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, 280, 160));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 255), 1, true), "Employee wise leave", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 1, 14), new java.awt.Color(51, 0, 255))); // NOI18N

        jLabel17.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(66, 73, 73));
        jLabel17.setText("Select department");

        departments.setEditable(true);
        departments.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        departments.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Select -", "Human Resource", "Production", "Sales & Marketing", "Purchasing", "Finance" }));
        departments.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        departments.setFocusable(false);
        departments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departmentsActionPerformed(evt);
            }
        });

        btn_view3.setBackground(new java.awt.Color(179, 182, 183));
        btn_view3.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btn_view3.setText("View");
        btn_view3.setBorder(null);
        btn_view3.setBorderPainted(false);
        btn_view3.setContentAreaFilled(false);
        btn_view3.setFocusPainted(false);
        btn_view3.setOpaque(true);
        btn_view3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_view3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_view3MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_view3MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_view3MouseReleased(evt);
            }
        });
        btn_view3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_view3ActionPerformed(evt);
            }
        });

        leave_month1.setEditable(true);
        leave_month1.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        leave_month1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Select -", "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        leave_month1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        leave_month1.setFocusable(false);
        leave_month1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leave_month1ActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(66, 73, 73));
        jLabel18.setText("Select");

        leave_year1.setEditable(true);
        leave_year1.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        leave_year1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        leave_year1.setFocusable(false);
        leave_year1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leave_year1ActionPerformed(evt);
            }
        });

        emp_name.setEditable(true);
        emp_name.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        emp_name.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Select -", "Human Resource", "Production", "Sales & Marketing", "Purchasing", "Finance" }));
        emp_name.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        emp_name.setFocusable(false);
        emp_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emp_nameActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(66, 73, 73));
        jLabel19.setText("Select employee");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                            .addComponent(jLabel18)
                            .addGap(35, 35, 35)
                            .addComponent(leave_year1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(leave_month1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel6Layout.createSequentialGroup()
                            .addComponent(jLabel17)
                            .addGap(6, 6, 6)
                            .addComponent(departments, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addGap(18, 18, 18)
                        .addComponent(emp_name, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_view3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(leave_year1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(leave_month1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(departments, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emp_name, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_view3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 50, 320, 160));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 255), 1, true), "Employee wise monthly attendance", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 1, 14), new java.awt.Color(51, 0, 255))); // NOI18N

        jLabel20.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(66, 73, 73));
        jLabel20.setText("Select department");

        departments1.setEditable(true);
        departments1.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        departments1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Select -", "Human Resource", "Production", "Sales & Marketing", "Purchasing", "Finance" }));
        departments1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        departments1.setFocusable(false);
        departments1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departments1ActionPerformed(evt);
            }
        });

        btn_view4.setBackground(new java.awt.Color(179, 182, 183));
        btn_view4.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btn_view4.setText("View");
        btn_view4.setBorder(null);
        btn_view4.setBorderPainted(false);
        btn_view4.setContentAreaFilled(false);
        btn_view4.setFocusPainted(false);
        btn_view4.setOpaque(true);
        btn_view4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_view4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_view4MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_view4MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_view4MouseReleased(evt);
            }
        });
        btn_view4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_view4ActionPerformed(evt);
            }
        });

        leave_month2.setEditable(true);
        leave_month2.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        leave_month2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Select -", "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        leave_month2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        leave_month2.setFocusable(false);
        leave_month2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leave_month2ActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(66, 73, 73));
        jLabel21.setText("Select");

        leave_year2.setEditable(true);
        leave_year2.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        leave_year2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        leave_year2.setFocusable(false);
        leave_year2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leave_year2ActionPerformed(evt);
            }
        });

        emp_name1.setEditable(true);
        emp_name1.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        emp_name1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Select -", "Human Resource", "Production", "Sales & Marketing", "Purchasing", "Finance" }));
        emp_name1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        emp_name1.setFocusable(false);
        emp_name1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emp_name1ActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(66, 73, 73));
        jLabel22.setText("Select employee");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel7Layout.createSequentialGroup()
                            .addComponent(jLabel21)
                            .addGap(35, 35, 35)
                            .addComponent(leave_year2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(leave_month2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel7Layout.createSequentialGroup()
                            .addComponent(jLabel20)
                            .addGap(6, 6, 6)
                            .addComponent(departments1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addGap(18, 18, 18)
                        .addComponent(emp_name1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_view4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(131, 131, 131))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(leave_year2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(leave_month2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(departments1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emp_name1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_view4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );

        jPanel2.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 320, -1));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 255), 1, true), "Department wise - Employee list", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 1, 14), new java.awt.Color(51, 0, 255))); // NOI18N

        btn_view5.setBackground(new java.awt.Color(179, 182, 183));
        btn_view5.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btn_view5.setText("View");
        btn_view5.setBorder(null);
        btn_view5.setBorderPainted(false);
        btn_view5.setContentAreaFilled(false);
        btn_view5.setFocusPainted(false);
        btn_view5.setOpaque(true);
        btn_view5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_view5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_view5MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_view5MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_view5MouseReleased(evt);
            }
        });
        btn_view5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_view5ActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(66, 73, 73));
        jLabel23.setText("Select department");

        departments2.setEditable(true);
        departments2.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        departments2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Select -", "Human Resource", "Production", "Sales & Marketing", "Purchasing", "Finance" }));
        departments2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        departments2.setFocusable(false);
        departments2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departments2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(departments2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 5, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_view5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(99, 99, 99))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(departments2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_view5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 50, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, 300, 140));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 255), 1, true), "Employee details ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 1, 14), new java.awt.Color(51, 0, 255))); // NOI18N

        jLabel24.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(66, 73, 73));
        jLabel24.setText("Select department");

        departments3.setEditable(true);
        departments3.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        departments3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Select -", "Human Resource", "Production", "Sales & Marketing", "Purchasing", "Finance" }));
        departments3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        departments3.setFocusable(false);
        departments3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departments3ActionPerformed(evt);
            }
        });

        btn_view6.setBackground(new java.awt.Color(179, 182, 183));
        btn_view6.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btn_view6.setText("View");
        btn_view6.setBorder(null);
        btn_view6.setBorderPainted(false);
        btn_view6.setContentAreaFilled(false);
        btn_view6.setFocusPainted(false);
        btn_view6.setOpaque(true);
        btn_view6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_view6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_view6MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_view6MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_view6MouseReleased(evt);
            }
        });
        btn_view6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_view6ActionPerformed(evt);
            }
        });

        emp_name2.setEditable(true);
        emp_name2.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        emp_name2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Select -", "Human Resource", "Production", "Sales & Marketing", "Purchasing", "Finance" }));
        emp_name2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        emp_name2.setFocusable(false);
        emp_name2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emp_name2ActionPerformed(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(66, 73, 73));
        jLabel26.setText("Select employee");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addGap(6, 6, 6)
                        .addComponent(departments3, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addGap(18, 18, 18)
                        .addComponent(emp_name2, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_view6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(departments3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emp_name2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_view6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        jPanel2.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 450, 320, 140));

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 25)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(41, 128, 185));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Reports - Attendance");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, -1));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 990, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 992, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 645, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void departmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_departmentActionPerformed

    private void jDateChooser1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jDateChooser1PropertyChange

    }//GEN-LAST:event_jDateChooser1PropertyChange

    private void btn_viewMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_viewMouseEntered
        btn_view.setBackground(new Color(144, 148, 151));
    }//GEN-LAST:event_btn_viewMouseEntered

    private void btn_viewMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_viewMouseExited
        btn_view.setBackground(new Color(179, 182, 183));
    }//GEN-LAST:event_btn_viewMouseExited

    private void btn_viewMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_viewMousePressed
        btn_view.setBackground(new Color(98, 101, 103));
    }//GEN-LAST:event_btn_viewMousePressed

    private void btn_viewMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_viewMouseReleased
        btn_view.setBackground(new Color(144, 148, 151));
    }//GEN-LAST:event_btn_viewMouseReleased

    private void btn_viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_viewActionPerformed
        
        try {
            String selected_date = new SimpleDateFormat("yyyy/MM/dd").format(jDateChooser1.getDate());
           
            String department_name = department.getSelectedItem().toString();
            String path = "iReport\\daily_attendance_sectionwise.jrxml";
            HashMap<String, Object> map = new HashMap<>();
            map.put("date", selected_date);
            map.put("department", department_name);
            
            JasperReport js = JasperCompileManager.compileReport(path);
            Connection c;
            Class.forName("com.mysql.jdbc.Driver");
            c = DriverManager.getConnection("jdbc:mysql://localhost:3307/central_insdustries", "root", "123");
            JasperPrint jp = JasperFillManager.fillReport(js, map, c);
            JasperViewer.viewReport(jp, false);
            c.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btn_viewActionPerformed

    private void btn_view1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_view1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_view1MouseEntered

    private void btn_view1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_view1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_view1MouseExited

    private void btn_view1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_view1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_view1MousePressed

    private void btn_view1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_view1MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_view1MouseReleased

    private void btn_view1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_view1ActionPerformed
        try {
            String selected_date = new SimpleDateFormat("yyyy/MM/dd").format(jDateChooser2.getDate());
            String path = "iReport\\all_attendance_daily.jrxml";
            HashMap<String, Object> map = new HashMap<>();
            map.put("date", selected_date);
            JasperReport js = JasperCompileManager.compileReport(path);
            Connection c;
            Class.forName("com.mysql.jdbc.Driver");
            c = DriverManager.getConnection("jdbc:mysql://localhost:3307/central_insdustries", "root", "123");
            JasperPrint jp = JasperFillManager.fillReport(js, map, c);
            JasperViewer.viewReport(jp, false);
            c.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btn_view1ActionPerformed

    private void jDateChooser2PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jDateChooser2PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jDateChooser2PropertyChange

    private void leave_depActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leave_depActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_leave_depActionPerformed

    private void btn_view2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_view2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_view2MouseEntered

    private void btn_view2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_view2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_view2MouseExited

    private void btn_view2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_view2MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_view2MousePressed

    private void btn_view2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_view2MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_view2MouseReleased

    private void btn_view2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_view2ActionPerformed

        try {

            int month = leave_month.getSelectedIndex();
            String Month = leave_month.getSelectedItem().toString();
            String year = leave_year.getSelectedItem().toString();
            String dep = leave_dep.getSelectedItem().toString();
            String path = "iReport\\leave_sectionwise.jrxml";
            HashMap<String, Object> map = new HashMap<>();
            map.put("year", year);
            map.put("month", month);
            map.put("department", dep);
            map.put("Month", Month);
            JasperReport js = JasperCompileManager.compileReport(path);
            Connection c;
            Class.forName("com.mysql.jdbc.Driver");
            c = DriverManager.getConnection("jdbc:mysql://localhost:3307/central_insdustries", "root", "123");
            JasperPrint jp = JasperFillManager.fillReport(js, map, c);
            JasperViewer.viewReport(jp, false);
            c.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btn_view2ActionPerformed

    private void leave_monthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leave_monthActionPerformed

    }//GEN-LAST:event_leave_monthActionPerformed

    private void leave_yearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leave_yearActionPerformed

    }//GEN-LAST:event_leave_yearActionPerformed

    private void departmentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departmentsActionPerformed
        String first_name;
        String sec_name;
        String emp_id;
        try {
            emp_name.removeAllItems();
            emp_name.addItem("-Select-");
            ResultSet rs = DB.search("SELECT id_employee,fname,mname FROM employee WHERE department='" + departments.getSelectedItem().toString() + "'");

            while (rs.next()) {
                first_name = rs.getString("fname");
                sec_name = rs.getString("mname");
                emp_id = rs.getString("id_employee");
                emp_name.addItem(emp_id + " - " + first_name + " " + sec_name);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_departmentsActionPerformed

    private void btn_view3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_view3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_view3MouseEntered

    private void btn_view3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_view3MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_view3MouseExited

    private void btn_view3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_view3MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_view3MousePressed

    private void btn_view3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_view3MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_view3MouseReleased

    private void btn_view3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_view3ActionPerformed
        try {
            String empid = emp_name.getSelectedItem().toString().split(" - ")[0].trim();
            int month = leave_month1.getSelectedIndex();
            String Month = leave_month1.getSelectedItem().toString();
            String year = leave_year1.getSelectedItem().toString();
            String dep = departments.getSelectedItem().toString();
            String path = "iReport\\empwise_leave.jrxml";
            HashMap<String, Object> map = new HashMap<>();
            map.put("year", year);
            map.put("month", month);
            map.put("department", dep);
            map.put("Month", Month);
            map.put("employee", empid);
            JasperReport js = JasperCompileManager.compileReport(path);
            Connection c;
            Class.forName("com.mysql.jdbc.Driver");
            c = DriverManager.getConnection("jdbc:mysql://localhost:3307/central_insdustries", "root", "123");
            JasperPrint jp = JasperFillManager.fillReport(js, map, c);
            JasperViewer.viewReport(jp, false);
            c.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btn_view3ActionPerformed

    private void leave_month1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leave_month1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_leave_month1ActionPerformed

    private void leave_year1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leave_year1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_leave_year1ActionPerformed

    private void emp_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emp_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emp_nameActionPerformed

    private void departments1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departments1ActionPerformed
        String first_name;
        String sec_name;
        String emp_id;
        try {
            emp_name1.removeAllItems();
            emp_name1.addItem("-Select-");
            ResultSet rs = DB.search("SELECT id_employee,fname,mname FROM employee WHERE department='" + departments1.getSelectedItem().toString() + "'");

            while (rs.next()) {
                first_name = rs.getString("fname");
                sec_name = rs.getString("mname");
                emp_id = rs.getString("id_employee");
                emp_name1.addItem(emp_id + " - " + first_name + " " + sec_name);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_departments1ActionPerformed

    private void btn_view4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_view4MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_view4MouseEntered

    private void btn_view4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_view4MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_view4MouseExited

    private void btn_view4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_view4MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_view4MousePressed

    private void btn_view4MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_view4MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_view4MouseReleased

    private void btn_view4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_view4ActionPerformed
        try {
            String empid = emp_name1.getSelectedItem().toString().split(" - ")[0].trim();
            int month = leave_month2.getSelectedIndex();
            String Month = leave_month2.getSelectedItem().toString();
            String year = leave_year2.getSelectedItem().toString();
            String dep = departments1.getSelectedItem().toString();
            String path = "iReport\\emp_monthly.jrxml";
            HashMap<String, Object> map = new HashMap<>();
            map.put("year", year);
            map.put("month", month);
            map.put("department", dep);
            map.put("Month", Month);
            map.put("employee", empid);
            JasperReport js = JasperCompileManager.compileReport(path);
            Connection c;
            Class.forName("com.mysql.jdbc.Driver");
            c = DriverManager.getConnection("jdbc:mysql://localhost:3307/central_insdustries", "root", "123");
            JasperPrint jp = JasperFillManager.fillReport(js, map, c);
            JasperViewer.viewReport(jp, false);
            c.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btn_view4ActionPerformed

    private void leave_month2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leave_month2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_leave_month2ActionPerformed

    private void leave_year2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leave_year2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_leave_year2ActionPerformed

    private void emp_name1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emp_name1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emp_name1ActionPerformed

    private void btn_view5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_view5MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_view5MouseEntered

    private void btn_view5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_view5MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_view5MouseExited

    private void btn_view5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_view5MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_view5MousePressed

    private void btn_view5MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_view5MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_view5MouseReleased

    private void btn_view5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_view5ActionPerformed
        try {
            String dep = departments2.getSelectedItem().toString();
            String path = "iReport\\sectionwise_emplist.jrxml";
            HashMap<String, Object> map = new HashMap<>();
            map.put("department", dep);
            JasperReport js = JasperCompileManager.compileReport(path);
            Connection c;
            Class.forName("com.mysql.jdbc.Driver");
            c = DriverManager.getConnection("jdbc:mysql://localhost:3307/central_insdustries", "root", "123");
            JasperPrint jp = JasperFillManager.fillReport(js, map, c);
            JasperViewer.viewReport(jp, false);
            c.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btn_view5ActionPerformed

    private void departments2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departments2ActionPerformed

    }//GEN-LAST:event_departments2ActionPerformed

    private void emp_name2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emp_name2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emp_name2ActionPerformed

    private void btn_view6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_view6ActionPerformed
        try {
            String empid = emp_name2.getSelectedItem().toString().split(" - ")[0].trim();
            String dep = departments3.getSelectedItem().toString();
            
            String path = "iReport\\emp_details.jrxml";
            HashMap<String, Object> map = new HashMap<>();
            map.put("department", dep);
            map.put("employee", empid);
            JasperReport js = JasperCompileManager.compileReport(path);
            Connection c;
            Class.forName("com.mysql.jdbc.Driver");
            c = DriverManager.getConnection("jdbc:mysql://localhost:3307/central_insdustries", "root", "123");
            JasperPrint jp = JasperFillManager.fillReport(js, map, c);
            JasperViewer.viewReport(jp, false);
            c.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btn_view6ActionPerformed

    private void btn_view6MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_view6MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_view6MouseReleased

    private void btn_view6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_view6MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_view6MousePressed

    private void btn_view6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_view6MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_view6MouseExited

    private void btn_view6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_view6MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_view6MouseEntered

    private void departments3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departments3ActionPerformed
        String first_name;
        String sec_name;
        String emp_id;
        try {
            emp_name2.removeAllItems();
            emp_name2.addItem("-Select-");
            ResultSet rs = DB.search("SELECT id_employee,fname,mname FROM employee WHERE department='" + departments3.getSelectedItem().toString() + "'");

            while (rs.next()) {
                first_name = rs.getString("fname");
                sec_name = rs.getString("mname");
                emp_id = rs.getString("id_employee");
                emp_name2.addItem(emp_id + " - " + first_name + " " + sec_name);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_departments3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(hrm_reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(hrm_reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(hrm_reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(hrm_reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new hrm_reports().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_view;
    private javax.swing.JButton btn_view1;
    private javax.swing.JButton btn_view2;
    private javax.swing.JButton btn_view3;
    private javax.swing.JButton btn_view4;
    private javax.swing.JButton btn_view5;
    private javax.swing.JButton btn_view6;
    private javax.swing.JComboBox<String> department;
    private javax.swing.JComboBox<String> departments;
    private javax.swing.JComboBox<String> departments1;
    private javax.swing.JComboBox<String> departments2;
    private javax.swing.JComboBox<String> departments3;
    private javax.swing.JComboBox<String> emp_name;
    private javax.swing.JComboBox<String> emp_name1;
    private javax.swing.JComboBox<String> emp_name2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    public static javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JComboBox<String> leave_dep;
    private javax.swing.JComboBox<String> leave_month;
    private javax.swing.JComboBox<String> leave_month1;
    private javax.swing.JComboBox<String> leave_month2;
    private javax.swing.JComboBox<String> leave_year;
    private javax.swing.JComboBox<String> leave_year1;
    private javax.swing.JComboBox<String> leave_year2;
    // End of variables declaration//GEN-END:variables

    private void loadtoYearcmb() {
        for (int i = 0; i < 100; i++) {
            int x = 2019;
            x = x + i;
            leave_year.addItem(x + "");
            leave_year1.addItem(x + "");
            leave_year2.addItem(x + "");
        }
    }

}
