package GUI;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JPanel;
import javax.swing.Timer;

public class Main_menu extends javax.swing.JFrame {
String loggeduser;
    public Main_menu() {
        initComponents();
        setSystemDate();
        setSystemTime();
    }
public String s2;
    public Main_menu(String text) {
        this();
        username.setText(text);
       s2= username.getText();
       loggeduser=text;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        date = new javax.swing.JLabel();
        time = new javax.swing.JLabel();
        production = new javax.swing.JButton();
        hr = new javax.swing.JButton();
        sales = new javax.swing.JButton();
        purchasing = new javax.swing.JButton();
        username = new javax.swing.JLabel();
        btn_Minimize = new javax.swing.JButton();
        btn_Exit = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        switch_user = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Central Industries|Main Menu");
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 128, 185), 2));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1366, 768));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        date.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        date.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 119, 45));

        time.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        time.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(time, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 91, 45));

        production.setBackground(new java.awt.Color(41, 128, 185));
        production.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        production.setForeground(new java.awt.Color(255, 255, 255));
        production.setText("Production Department");
        production.setBorder(null);
        production.setBorderPainted(false);
        production.setContentAreaFilled(false);
        production.setFocusPainted(false);
        production.setOpaque(true);
        production.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                productionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                productionMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                productionMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                productionMouseReleased(evt);
            }
        });
        production.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productionActionPerformed(evt);
            }
        });
        jPanel1.add(production, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 75, 170, 40));

        hr.setBackground(new java.awt.Color(41, 128, 185));
        hr.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        hr.setForeground(new java.awt.Color(255, 255, 255));
        hr.setText("H/R Department");
        hr.setBorder(null);
        hr.setBorderPainted(false);
        hr.setContentAreaFilled(false);
        hr.setFocusPainted(false);
        hr.setOpaque(true);
        hr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                hrMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                hrMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                hrMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                hrMouseReleased(evt);
            }
        });
        hr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hrActionPerformed(evt);
            }
        });
        jPanel1.add(hr, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 75, 170, 40));

        sales.setBackground(new java.awt.Color(41, 128, 185));
        sales.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        sales.setForeground(new java.awt.Color(255, 255, 255));
        sales.setText("Sales & Marketing");
        sales.setBorder(null);
        sales.setBorderPainted(false);
        sales.setContentAreaFilled(false);
        sales.setFocusPainted(false);
        sales.setOpaque(true);
        sales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                salesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                salesMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                salesMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                salesMouseReleased(evt);
            }
        });
        sales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salesActionPerformed(evt);
            }
        });
        jPanel1.add(sales, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 75, 170, 40));

        purchasing.setBackground(new java.awt.Color(41, 128, 185));
        purchasing.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        purchasing.setForeground(new java.awt.Color(255, 255, 255));
        purchasing.setText("Purchasing Department");
        purchasing.setBorder(null);
        purchasing.setBorderPainted(false);
        purchasing.setContentAreaFilled(false);
        purchasing.setFocusPainted(false);
        purchasing.setOpaque(true);
        purchasing.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                purchasingMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                purchasingMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                purchasingMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                purchasingMouseReleased(evt);
            }
        });
        purchasing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purchasingActionPerformed(evt);
            }
        });
        jPanel1.add(purchasing, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 75, 170, 40));

        username.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        username.setForeground(new java.awt.Color(255, 255, 255));
        username.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        username.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                usernameInputMethodTextChanged(evt);
            }
        });
        jPanel1.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 10, 100, 40));

        btn_Minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/mini1.png"))); // NOI18N
        btn_Minimize.setBorder(null);
        btn_Minimize.setContentAreaFilled(false);
        btn_Minimize.setFocusPainted(false);
        btn_Minimize.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/mini2.png"))); // NOI18N
        btn_Minimize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_MinimizeActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(1296, 2, 34, 32));

        btn_Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Close_black.png"))); // NOI18N
        btn_Exit.setBorder(null);
        btn_Exit.setContentAreaFilled(false);
        btn_Exit.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Close_red_.png"))); // NOI18N
        btn_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ExitActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 2, 34, 32));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/panel2bk.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 140, 220, 570));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/KtK_main.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, 1120, 620));

        jSeparator2.setForeground(new java.awt.Color(41, 128, 179));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 140, 10, 610));

        switch_user.setBackground(new java.awt.Color(41, 128, 185));
        switch_user.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        switch_user.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Change_User.png"))); // NOI18N
        switch_user.setText("Switch User");
        switch_user.setBorder(null);
        switch_user.setBorderPainted(false);
        switch_user.setContentAreaFilled(false);
        switch_user.setFocusPainted(false);
        switch_user.setOpaque(true);
        switch_user.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                switch_userMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                switch_userMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                switch_userMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                switch_userMouseReleased(evt);
            }
        });
        switch_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                switch_userActionPerformed(evt);
            }
        });
        jPanel1.add(switch_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 710, 181, 36));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/User.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setFocusPainted(false);
        jButton2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user_roll.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 10, 40, 40));

        jLabel1.setBackground(new java.awt.Color(41, 128, 185));
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 75, 1360, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleDescription("Central Industries|Main Menu");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btn_ExitActionPerformed

    private void hrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hrActionPerformed
        main_hrm h = new main_hrm(this);
        jPanel2.removeAll();
        jPanel2.revalidate();
        jPanel2.repaint();
        jPanel2.add((JPanel) h.jPanel1);
       // jPanel3.removeAll();
        jPanel3.revalidate();
        jPanel3.repaint();
        h = null;
        System.gc();
    }//GEN-LAST:event_hrActionPerformed

    private void productionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productionActionPerformed
        main_production p = new main_production(this);
        jPanel2.removeAll();
        jPanel2.revalidate();
        jPanel2.repaint();
        jPanel2.add((JPanel) p.jPanel1);
        //jPanel3.removeAll();
        jPanel3.revalidate();
        jPanel3.repaint();
        p = null;
        System.gc();
    }//GEN-LAST:event_productionActionPerformed

    private void salesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salesActionPerformed
        main_sales s = new main_sales(this);
        jPanel2.removeAll();
        jPanel2.revalidate();
        jPanel2.repaint();
        jPanel2.add((JPanel) s.jPanel1);
       // jPanel3.removeAll();
        jPanel3.revalidate();
        jPanel3.repaint();
        s = null;
        System.gc();
    }//GEN-LAST:event_salesActionPerformed

    private void purchasingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purchasingActionPerformed
        main_purchasing pur = new main_purchasing(this);
        jPanel2.removeAll();
        jPanel2.revalidate();
        jPanel2.repaint();
        jPanel2.add((JPanel) pur.jPanel1);
       // jPanel3.removeAll();
        jPanel3.revalidate();
        jPanel3.repaint();
        pur = null;
        System.gc();
    }//GEN-LAST:event_purchasingActionPerformed

    private void hrMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hrMouseEntered
        hr.setBackground(new Color(31, 97, 141));
    }//GEN-LAST:event_hrMouseEntered

    private void hrMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hrMouseExited
        hr.setBackground(new Color(41, 128, 185));
    }//GEN-LAST:event_hrMouseExited

    private void productionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productionMouseEntered
        production.setBackground(new Color(31, 97, 141));
    }//GEN-LAST:event_productionMouseEntered

    private void salesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salesMouseEntered
        sales.setBackground(new Color(31, 97, 141));
    }//GEN-LAST:event_salesMouseEntered

    private void purchasingMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_purchasingMouseEntered
        purchasing.setBackground(new Color(31, 97, 141));
    }//GEN-LAST:event_purchasingMouseEntered

    private void productionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productionMouseExited
        production.setBackground(new Color(41, 128, 185));
    }//GEN-LAST:event_productionMouseExited

    private void salesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salesMouseExited
        sales.setBackground(new Color(41, 128, 185));
    }//GEN-LAST:event_salesMouseExited

    private void purchasingMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_purchasingMouseExited
        purchasing.setBackground(new Color(41, 128, 185));
    }//GEN-LAST:event_purchasingMouseExited

    private void switch_userMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_switch_userMouseEntered
        switch_user.setBackground(new Color(31, 97, 141));
    }//GEN-LAST:event_switch_userMouseEntered

    private void switch_userMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_switch_userMouseExited
        switch_user.setBackground(new Color(41, 128, 185));
    }//GEN-LAST:event_switch_userMouseExited

    private void hrMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hrMousePressed
        hr.setBackground(new Color(21, 67, 96));
    }//GEN-LAST:event_hrMousePressed

    private void hrMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hrMouseReleased
        hr.setBackground(new Color(31, 97, 141));
    }//GEN-LAST:event_hrMouseReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Change_UserPassword p = new Change_UserPassword(this, username.getText());
        p.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void productionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productionMousePressed
        production.setBackground(new Color(21, 67, 96));
    }//GEN-LAST:event_productionMousePressed

    private void productionMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productionMouseReleased
        production.setBackground(new Color(31, 97, 141));
    }//GEN-LAST:event_productionMouseReleased

    private void salesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salesMousePressed
        sales.setBackground(new Color(21, 67, 96));
    }//GEN-LAST:event_salesMousePressed

    private void salesMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salesMouseReleased
        sales.setBackground(new Color(31, 97, 141));
    }//GEN-LAST:event_salesMouseReleased

    private void purchasingMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_purchasingMousePressed
        purchasing.setBackground(new Color(21, 67, 96));
    }//GEN-LAST:event_purchasingMousePressed

    private void purchasingMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_purchasingMouseReleased
        purchasing.setBackground(new Color(31, 97, 141));
    }//GEN-LAST:event_purchasingMouseReleased

    private void switch_userMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_switch_userMousePressed
        switch_user.setBackground(new Color(21, 67, 96));
    }//GEN-LAST:event_switch_userMousePressed

    private void switch_userMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_switch_userMouseReleased
        switch_user.setBackground(new Color(31, 97, 141));
    }//GEN-LAST:event_switch_userMouseReleased

    private void switch_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_switch_userActionPerformed
        Login log = new Login();
        log.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_switch_userActionPerformed

    private void btn_MinimizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_MinimizeActionPerformed
        this.setState(Main_menu.ICONIFIED);
    }//GEN-LAST:event_btn_MinimizeActionPerformed

    private void usernameInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_usernameInputMethodTextChanged
       // TODO add your handling code here:
    }//GEN-LAST:event_usernameInputMethodTextChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Exit;
    private javax.swing.JButton btn_Minimize;
    private javax.swing.JLabel date;
    private javax.swing.JButton hr;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel2;
    public final javax.swing.JPanel jPanel3 = new javax.swing.JPanel();
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton production;
    private javax.swing.JButton purchasing;
    private javax.swing.JButton sales;
    private javax.swing.JButton switch_user;
    private javax.swing.JLabel time;
    private javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables

    private void setSystemTime() {
        SimpleDateFormat sdf = new SimpleDateFormat("hh:mm:ss a");
        Timer t = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date d = new Date();
                time.setText(sdf.format(d));
                d = null;
            }
        });
        t.start();
    }

    private void setSystemDate() {
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        Timer t = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date d = new Date();
                date.setText(sdf.format(d));
                d = null;
            }
        });
        t.start();
    }

}
